sudo: required
language: node_js
node_js:
  - '12'
install:
  - npm run install:deps
script:
  - npm run setup
  - npm run lint
  - npm run test
after_success:
  - npm run coverage
cache:
  directories:
    - node_modules
